### ISSUE TITLE
Refactor Player

### ISSUE THREAD

**Issue by LaraMo** [LaraMo/Risk-Swift-Sloths#23]
- [x] Above every function - create proper comments for each function

For getter and setters, no comment is needed, but have the proper naming.
Have the following format:
```js
/** 
* This method returns number of ....
*/
void getNumberOfPeople();
```

- [x] correct copy constructor, assignment operator, and stream insertion operator
- [x] Make sure new pointer pointers point at proper memory loction

**Comment by EyalAzimov** [comment]
Great Job!! 

I'm closing this bad boy for you!
