### ISSUE TITLE
Refactor Orderlist

### ISSUE THREAD

**Issue by LaraMo** [LaraMo/Risk-Swift-Sloths#26]
- [x] Above every function - create proper comments for each function

For getter and setters, no comment is needed, but have the proper naming.
Have the following format:
```js
/** 
* This method returns number of ....
*/
void getNumberOfPeople();
```

- [x] Correct copy constructor, assignment operator, and stream insertion operator
- [x] Make sure new pointer pointers point at proper memory loction  

- [x] Make order list a `vector`

**Comment by EyalAzimov** [comment]
All done!
See Branch order-execution-implementation
